server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=Asia/Seoul
    username: yh
    password: 1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    #show-sql: true
    #properties:
      #hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1054020609574-1hvkvqvuf2gklovnjae39m1hfcme7sl3.apps.googleusercontent.com
            client-secret: HLB8mKm_A62CCKhSIgTzQoXr
            scope:
            - email
            - profile
            
          facebook:
            client-id: 577078206996719
            client-secret: d21b77d52ef891c559cc45af32d97002
            scope:
            - email
            - public_profile
            
          kakao:
            client-id: 9f2407a32eb59fd6f8274ae8c537b676
            scope:
            - profile_nickname
            - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/kakao
            
          naver:
            client-id: qHu_kSd83pEJqvuS9nMg
            client-secret: MSbvsaAV_o
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code # 코드를 받는다
            redirect-uri: http://localhost:8000/login/oauth2/code/naver # 콜백 주소
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 로그인 창이 뜸
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰 받기
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보 받기
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
          
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 로그인 창이 뜸
            token-uri: https://kauth.kakao.com/oauth/token # 토큰 받기
            user-info-uri: https://kapi.kakao.com/v2/user/me # 프로필 정보 받기
            user-name-attribute: id # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
